# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 088aaa8439fe32beb153fd5692eb62bafdd87a83c2fbee714cb32ba76766ea7c44a2df905d3b268976b05ee65d526d554036084ad3589e65c8614b6e18d96b98

test:
  secret_key_base: d605287deed4c573e1b38b1165bc364fdf4f019cfd381a7f79f85c8c3452597f4dd1efa9c5218199ff6a0b2ab8607c31adf75003130927b13a63993c0701b83e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 8f9ac232fe892bf97ca05bf843e4d42e024c8084fe94ab1eb39c3165cdadcb8ca6e3f3d2ae2d387bd34ccd144a7ba6f73ce781d6e71aef4ed29730837454a495
